ryceg/Eigengrau-s-Essential-Establishment-Generator

- EssentialEstablishmentGenerator/Settings/CSS/stylesheet.css
This code is to remove the link icons from below image links that are imposed by Twine.
> Remove Link Icons from Image Links

- README.md
Right now it links to https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/blob/master/www.reddit.com/r/EigengrausGenerator which is a 404 page.
> Fix broken Reddit link

- EssentialEstablishmentGenerator/Meta/Changelog.twee
- EssentialEstablishmentGenerator/Meta/ChangelogFull.twee
This aims to update the change log lists from basic dash-prefixed span elements, to semantically correct [html lists](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul).
I have not compiled and verified that this is all working out of the box, so it would be great if somebody could verify that it does.
> Update change log lists to semantic html lists

- EssentialEstablishmentGenerator/Meta/PatreonSupporters.twee
[Apparently](http://twinery.org/wiki/syntax), the official way to make an unordered list in Twine is to use `*` syntax.
This is converted into `ul` and `li` tags upon compilation.
This PR applies this to the Patreon supporter list.
> Use twine list syntax for Patreon supporter list

- EssentialEstablishmentGenerator/Meta/Changelog.twee
- EssentialEstablishmentGenerator/Meta/ChangelogFull.twee
Removes the extra line breaks introduced when formatting the changelogs.
> Fix line breaks in changelog

- README.md
- main.ejs
- package.json
- scripts/build.js
- scripts/postinstall.js
- scripts/utils.js
- yarn.lock
- Adds script for downloading tweego files on `postinstall`
- Adds script for simpler building
- Updates the readme.
- Converts the main file to a nicer format.
So now all you have to do is `yarn` to install everything required, and then `yarn build` or `yarn start`.
This should greatly simplify on-boarding.
> Add automatic tweego downloading

- scripts/postinstall.js
Fixes a bug where the correct folder would not be created when unzipping story formats.
> Fix postinstall folder creation

- .eslintrc
Enables linting rules for [`no-var`](https://eslint.org/docs/rules/no-var), [`prefer-const`](https://eslint.org/docs/rules/prefer-const) & [`object-shorthand`](https://eslint.org/docs/rules/object-shorthand)
> Enforces let const and object shorthand

- CHANGELOG.md
Formats the change log markdown file closer to the rules specified by [markdownlint](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md)
> Format change log

- .eslintrc
```javascript
const obj = {
'prop1': value // => prop1, because none of the props need quotes
prop2: value
}
```
```javascript
const obj = {
'prop-1': value 
prop2: value // => 'prop2', because one of the props has a name that needs quotes
}
```
> Add eslint rule for consistent qoutes on props

- EssentialEstablishmentGenerator/Settings/CSS/stylesheet.css
- EssentialEstablishmentGenerator/Settings/StoryStuff/StoryAuthor.twee
- EssentialEstablishmentGenerator/Settings/StoryStuff/StoryMenu.twee
- EssentialEstablishmentGenerator/Start/Start.twee
This also removes the welcome message to streamline the first page and have more of the actual generator visible as soon as the user comes to the site
> Migrate Version Number to toolbar

- EssentialEstablishmentGenerator/Tools/clampRolls.js
The two removed lines didn't actually do anything, to the best of my knowledge.
Neither one modifies the original value.
> Remove redundant clamp calls

- EssentialEstablishmentGenerator/Factions/allies.js
`Array.concat` does not modify the original array, so this line does nothing.
> Remove unused concat

- EssentialEstablishmentGenerator/Settings/StoryStuff/StoryTitle.twee
Fixed https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/issues/239.
Newlines in StoryTitle.twee caused an unexpected line break in the JS source code.
> Fixed the generator not loading

- __tests__/GeneralStoreRenders.test.js
File names are case sensitive on Linux, causing: 
```bash
$ yarn test
yarn run v1.19.0
$ jest
FAIL  __tests__/GeneralStoreRenders.test.js
● Test suite failed to run
Cannot find module '../EssentialEstablishmentGenerator/GeneralStore/JS/GeneralStoreRenders' from 'GeneralStoreRenders.test.js'
2 | global.setup = {}
3 | global.random = (min, max) => { return (min + max) / 2 } // mock random global func to be deterministic
> 4 | require('../EssentialEstablishmentGenerator/GeneralStore/JS/GeneralStoreRenders')
| ^
5 | 
6 | const store = {
7 |   roll: {
at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
at Object.require (__tests__/GeneralStoreRenders.test.js:4:1)
```
**Note**: Depends on https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/pull/237 for …
> Fixes GeneralStoreRenders test on Linux

- .vscode/extensions.json
- .vscode/settings.json
Adds some very basic syntax highlighting for twine. Requires the `Highlight` extension for VSCode.
> Add twine syntax highlighting

- .eslintrc
- global.d.ts
- jsconfig.json
- package.json
- src/Buildings/buildingData.js
- src/setup.d.ts
- yarn.lock
Adds type declarations for non-native methods/functions/constants. This totally replaces the old eslint globals flags.
Enables adding type declarations for properties on the `setup` object.
(see `./src/setup.d.ts` for en example)
This has the potential to catch a lot of bugs resulting from typos, as well as abstracting types to a singe source of truth. This also has some very convenient side effects, such as being able to rename things globally with a single key stroke. To try this out, see `./src/setup.d.ts` again and rename something with `F2` in VSCode.
> Improve editor experience

- .eslintignore
- .gitignore
- lib/index.ts
- lib/random.ts
- lib/tsconfig.json
- main.ejs
- package.json
- scripts/build.js
- scripts/webpack.config.js
- src/init.js
- webpack.config.js
- yarn.lock
Adds a new `lib/`-folder, which at compile time is bundled into a javascript file. This `lib` folder, and everything in it has full typescript support.
To expose something to the rest of the code, the thing you want to expose must be exported in some way via the `lib/index.ts`-file. The exported function should then be fully available via `lib.myExportedFunction()`.
Debugging of code originating from within `lib` should be a *huge* improvement over the current workflow due to full source map support.
Anything within `lib` will not have access to the Sugarcube syntax, so if you want to use sugarcube stuff, you'll have to pass it into the called function. 
For example
```ts
lib.myExportedFunction(State.temporary)
```
> Typescript support

- lib/npc-generation/setAge.ts
#312 Age descriptors are broken in the compiled version (all NPCs show as newborn)
This was a simple comparison error. It loops through the age threshold in descending order, but was looking for the threshold to be less than the NPC age. This was always true for newborn. I simply switched the comparison direction. Not sure why it doesn't cause an issue in the live version (as of 8/25/2020). But a simple fix.
> #312 - fix

- scripts/build.js
After a hasty readthrough of the README, I ran the start before installing the compiler and received an assortment of errors. Adding this brief check at the start of the build script will help catch any developer that makes the same mistake.
> Add check in build script that tweego was installed

- src/World/encounters.d.ts
- src/World/locations.d.ts
- src/World/locations.js
- src/World/miscData.js
It refactors `setup.misc.locations` from an object into an array.
Manually, in the UI.
Nope?
> Refactor locations list

- src/PlotHook/plothooks.js
- Refactor setup.plothooks from object to array of objects, change the original object's key to "summary" property in the new object.
https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/issues/359
> Refactor setup.plothooks into an array

- scripts/build.js
I pulled this project and tried building it, but ran into some cryptic errors when running the `build.js` script. It turns out the problem was that the executable at `.twine/tweego` did not have permissions to execute on my machine.
This Pull Request adds a check at the top of the build.js script to provide a more user friendly error and a recommended solution.
I ran `chmod -x .twine/tweego` and verified that the process halted and displayed my error message. I then ran `chmod +x .twine/tweego` and verified that the process continues along happily.
⚠️This solution has only been tested on a macbook. I suspect this won't work properly on Windows machines. I could use some help with suggestions for how to make it windows friendly if that is something this project cares about!
I don't think …
> Add executable permissions check for tweego on Unix systems

- lib/src/weightRandom.ts
Improves the handling of unexpected weighted random rolls, as discussed [here](https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/pull/352#discussion_r502205574).
```js
for (let i = 0; i <= 1000000; i++) {
weightRandom({ a: 1, b: 2, c: 3 })
}
// No errors were thrown
```
No.
Yes.
> Replace fallback value with error in weightRandom

- README.md
- package.json
- scripts/webpack.config.js
- src/Settings/CSS/stylesheet.css
- src/Start/Start.twee
- yarn.lock
- Adds `CopyWebpackPlugin`
- Modifies image paths in tweego file
Tested locally. 
https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/issues/400
Yes
All images are resolving locally now.
> Adds webpack plugin that copies over images for local development

- scripts/rollup.config.js
- tsconfig.json
I realized shortly after checking out this branch that a typical import/export strategy won't work especially well here. Specifically, while a relative import will "work", it'll also import the code from that module into `main.js` regardless of whether or not it's already being included in the `lib` file. That could lead to a lot of inadvertent duplication.
So, to head this off, I've updated the Rollup and TypeScript configuration to include a path alias for a `@lib` module that points to the `lib` global introduced by that file.
```typescript
import { bandits } from '@lib';                           // yay
import { bandits } from '../../../lib/constructs/bandits' // nay, duplicates code
```
...and independent from the content of the PR, I think exporting data interfaces from within …
> Adds TS/Rollup module path configuration.

- scripts/rollup.config.js
Reenables source maps for `lib`, and turns on inline source maps for the `src` code.
> Reenable source maps

- src/Start/CreateBuilding.twee
Fixes an error when trying to highlight new buildings. Apparently the tippy refactor broke it.
Tested in the HTML.
I don't think so?
> Fix highlighting of new buildings

- lib/npc-generation/_common.ts
- lib/npc-generation/createName.ts
- lib/npc-generation/raceTraits.ts
- lib/npc-generation/setRace.ts
- lib/src/genderData.ts
- lib/town/_common.ts
- src/NPCGeneration/createNPC.ts
Adds nonbinary as a gender option.
Tested in the `.html`.  Editing an NPC to be nonbinary works, and their gender updates correctly in the profile, but not in other contexts; a female bartender will still use female pronouns when changed to nonbinary.
> Add-nonbinary

- lib/src/createRing.ts
-Add comments to lists so they're easier to parse
-Adds on to existing ring lists
Used the html file
Nah
> Expanding on getRing

- lib/npc-generation/raceTraits.ts
- src/NPCGeneration/createNPC.ts
Fix the comparison to see if the last name is empty 
Tested locally
> Fix last name comparison

- src/Start/StoryInit.twee
Adds an initialisation of customImages
Should work fine
> Adds an initialisation of customImages

- src/Religion/Components/Followers.twee
Fix underworshipped deities not rendering percentage properly
> Fix underworshipped deities not rendering percentage properly

- lib/src/findInContainer.ts
- src/Settings/Tippy/tooltips.ts
- src/Tools/profile.ts
Fixes type errors in the build. Stolen from `refactoring-js` branch! Thanks!
Saw some tooltips
Nope - builds are failing though. This should fix the failures because of type checking not working.
> Fixing type errors in build

- lib/npc-generation/professions.ts
Adds female versions of professions that are gendered- queens to kings, duchesses to dukes, etc. Ideally this would be handled by adding the data so that gendered professions had synonym versions, but I couldn't be bothered to do that.
It's just adding in a bunch of new professions, no need for testing. 
Closes #700
> Add female versions of professions- quick and dirty fix

- lib/general-store/_common.ts
- lib/general-store/generalStoreRenders.test.ts
- lib/general-store/generalStoreRenders.ts
Since the `size` calculation was moved to be a threshold table, the weight changed by 1 since it does a `>=` instead of a `>`-operation. So this changes the expected test result to reflect that.
This also updates the types so that `generalStoreRenders` accepts specifically the object shape it needs, which means we don't need to pass an entire `GeneralStore` object to use it.
> Fix general generalStoreRenders test

- lib/npc-generation/npcFinances.ts
- lib/town/_common.ts
- lib/town/getTaxRate.ts
- src/NPCGeneration/NPCProfile/Components/NPCIncomeTable.twee
- src/Town/js/createTown.ts
Removes a few getters from the town object by calculating taxes based on rolls on the fly.
Also cleans up the `npcTaxRate` function.
> Remove tax getters from town object

- src/main.ts
Fixes a crash from trying to reference a function which is no longer available.
> fix broken createTownName reference

- lib/src/tippy.ts
- lib/src/treasureMap.ts
- src/World/encounters.ts
- src/World/miscData.js
Removes the `createTippy` & `createTippyWord` utils in favour of always creating the full tippy.
> Cleanup partial tippys

- lib/src/inventory.ts
Modifies inventory.ts to resolve issue #695 where alchemist inventory doesn't contain consumables
Fix was confirmed in compiled html file
#695
> resolution for issue #695

- src/Blacksmith/js/createSmithy.ts
- src/MiniEstablishments/Guardhouse/createGuardhouse.ts
Modifies smithy and guardhouse creation code to resolve issue #630 where the respective buildings aren't added to the correct road when being created from a road page.
Fix was tested and verified in compiled html. 
#630
> Fixes for issue #630, smithy and guardhouse not created on specific road

- src/Start/CreateBuilding.twee
- src/Town/components/TownListBuildings.twee
Adds the CreateBuilding button as found on the start page to the 'Detailed Description'  screen.
Built and manually tested behaviour on start screen and details screen.
#750
> Added CreateBuilding button to Detailed Description screen #750

- lib/alchemist/alchemistRollData.ts
- lib/town/townData.ts
Includes additional road names and one road type
Ensured application could build. Lint and tests pass
No
> Added more street name combinations based on lower Manhattan
