- EssentialEstablishmentGenerator/Factions/factionData.js
- EssentialEstablishmentGenerator/MiniEstablishments/marketData.js
- EssentialEstablishmentGenerator/PlotHook/plothookData.js
- EssentialEstablishmentGenerator/Town/js/guardData.js
Add:
New Faction - Foreign dignitaries/embassy
Market Options
Guard Options
Plot Hooks
> Add to more lists

- EssentialEstablishmentGenerator/Factions/factionData.js
- EssentialEstablishmentGenerator/PlotHook/plothook.js
- EssentialEstablishmentGenerator/World/miscData.js
Fixed some of the old style plot hooks.
Added a start for the Druids and Clergy factions, both need more options
Added a bunny to the animal generator
You might want to check my syntax, I had to guess for a lot of the quest functionality pieces.
> Fixed some of the old style plot hooks

- EssentialEstablishmentGenerator/MiniEstablishments/CreateTemple.js
- EssentialEstablishmentGenerator/MiniEstablishments/TempleOutput.twee
- EssentialEstablishmentGenerator/MiniEstablishments/templeData.js
Reworks the temple format and moves the sentence generation into createTemple.js
-Adds architect to temples
> Temple Format Update

- EssentialEstablishmentGenerator/Factions/age.js
> Refactor age.js

- README.md
I tried to make it a bit clearer, let me know if there's anything that needs changing.
> Try to clear up compiling instructions

- EssentialEstablishmentGenerator/World/miscData.js
Lambdas have several advantages over regular functions
> Use lambdas

- EssentialEstablishmentGenerator/NPCGeneration/professions.js
Not completely filled out, but new information is ready to be added in the template
> Updated new roles into file, missing some information

- EssentialEstablishmentGenerator/Blacksmith/JS/blacksmithData.js
- EssentialEstablishmentGenerator/Blacksmith/JS/createBlacksmith.js
- EssentialEstablishmentGenerator/Blacksmith/JS/createSmithy.js
- EssentialEstablishmentGenerator/Blacksmith/JS/createSmithyName.js
Formats the blacksmith js code to comply with the code style.
> Format blacksmith es to the eslint guidelines

- EssentialEstablishmentGenerator/Alchemist/js/alchemistData.js
- EssentialEstablishmentGenerator/Alchemist/js/createAlchemist.js
- EssentialEstablishmentGenerator/Alchemist/js/createAlchemistName.js
- EssentialEstablishmentGenerator/Alchemist/js/createChemist.js
Formats the alchemist js code to comply with the current code style.
> Format alchemist js to the eslint guidelines

- EssentialEstablishmentGenerator/Start/Popup.twee
It took me to https://eigengrausgenerator.com/www.reddit.com/r/EigengrausGenerator otherwise
> Fix broken link

- EssentialEstablishmentGenerator/Buildings/buildingData.js
- EssentialEstablishmentGenerator/MiniEstablishments/CreateTemple.js
- EssentialEstablishmentGenerator/MiniEstablishments/templeData.js
- EssentialEstablishmentGenerator/NPCGeneration/professions.js
- EssentialEstablishmentGenerator/World/locations.js
Expands upon the naming system for temples and places the temple building descriptors inside of createTemple.js
> Temple additions

- EssentialEstablishmentGenerator/Tools/FindInObject.js
- EssentialEstablishmentGenerator/Tools/clampRolls.js
- EssentialEstablishmentGenerator/Tools/contentsFetcher.js
- EssentialEstablishmentGenerator/Tools/defineRollDataGetter.js
- EssentialEstablishmentGenerator/Tools/factionsForType.js
- EssentialEstablishmentGenerator/Tools/fetchProfessions.js
- EssentialEstablishmentGenerator/Tools/objectArrayFetcher.js
- EssentialEstablishmentGenerator/Tools/weightedRandomFetcher.js
Converts a lot of inline comments into jsdoc documentation.
> Improve documentation

- .eslintrc
- EssentialEstablishmentGenerator/Buildings/createBuilding.js
- EssentialEstablishmentGenerator/Factions/leader.js
- EssentialEstablishmentGenerator/Factions/resources.js
- EssentialEstablishmentGenerator/Settings/Plugins/seededRandom.js
- EssentialEstablishmentGenerator/Settings/Setting.js
- EssentialEstablishmentGenerator/Settings/Tippy/tooltips.js
- EssentialEstablishmentGenerator/Tavern/js/createTavern.js
- EssentialEstablishmentGenerator/Tavern/js/tavernBrawl.js
- EssentialEstablishmentGenerator/Tools/closestMatch.js
- EssentialEstablishmentGenerator/Tools/weightedRandomFetcher.js
- EssentialEstablishmentGenerator/Town/Weather/js/createWeather.js
- EssentialEstablishmentGenerator/Town/Weather/js/renderWeather.js
- EssentialEstablishmentGenerator/Town/Weather/js/weather.js
- EssentialEstablishmentGenerator/Town/js/createGuard.js
- EssentialEstablishmentGenerator/Town/js/createNewBuilding.js
- EssentialEstablishmentGenerator/Town/js/createStartFactions.js
- EssentialEstablishmentGenerator/Town/js/createTownName.js
- EssentialEstablishmentGenerator/Town/js/guardData.js
- EssentialEstablishmentGenerator/Town/js/linguisticDrift.js
- __tests__/GeneralStoreRenders.test.js
Fixes all linting errors. Might need a lookover to see I didn't break anything.
> Fix all linting errors

- EssentialEstablishmentGenerator/Tools/FindInContainer.js
This should eliminate a lot of errors when creating scenarios.
> Checks that value is array before calling include

- EssentialEstablishmentGenerator/MiniEstablishments/MarketsOutput.twee
- EssentialEstablishmentGenerator/MiniEstablishments/createMarket.js
- EssentialEstablishmentGenerator/MiniEstablishments/marketData.js
Divides the merchants from the market description with a sub-header. Adds a crowd descriptor. Other minor tweaks.
> Feature/Market Tweak

- EssentialEstablishmentGenerator/Buildings/buildingData.js
- EssentialEstablishmentGenerator/Buildings/createBuilding.js
- EssentialEstablishmentGenerator/Town/js/createTown.js
- EssentialEstablishmentGenerator/Town/js/createTownMaterial.js
- EssentialEstablishmentGenerator/Town/js/townData.js
closes #205 
- Creates the `townMaterial` property in the town object, this property is generated based in the town location, size and wealth.
- added material '_tiers_' .
- Building material is influenced by town material and building wealth.
> Town Building Material

- EssentialEstablishmentGenerator/Tools/weightRandom.js
- EssentialEstablishmentGenerator/Town/js/createTown.js
- EssentialEstablishmentGenerator/Town/js/townData.js
> Refactor location vegetation and plants to an array of integers

- .github/workflows/main.yml
- __tests__/GeneralStoreRenders.test.js
- __tests__/matchFirst.test.js
- global.d.ts
- package.json
- scripts/build.js
- src/GeneralStore/JS/generalStoreRenders.js
- yarn.lock
Adds continuous integration via GitHub actions
> Setup continuous integration

- global.d.ts
- src/Misc/createMercenaries.js
- src/Settings/Tippy/tippy.d.ts
- src/Settings/Tippy/tippy.js
- src/Town/Weather/js/renderWeather.js
- src/World/miscData.js
Adds a few utilities to reduce the duplucation of the tippy definitions.
Also somehow fixes the bug that some elements does not get tippy applied.
> Add tippy utilities

- src/Town/js/townData.js
#275 - Updates the description for politicalSource 'republic' in townData.js
> Update description for republic

- src/Tavern/Rooms.twee
- src/Tavern/js/tavernRooms.d.ts
- src/Tavern/js/tavernRooms.js
Avoids storing `freeRooms` on the tavern, and instead calculates it when required.
I'm a bit unsure about the SugarCube syntax, so someone double check it for me.
> Update free rooms function

- lib/index.ts
- lib/src/clampRolls.ts
- src/Alchemist/InitAlchemist.twee
- src/Blacksmith/InitSmithy.twee
- src/GeneralStore/InitGeneralStore.twee
- src/Tavern/InitTavern.twee
- Moves the `clampRolls` utility into `lib`. 
- Removes the unused return value.
> Move clampRolls into lib

- src/Settings/CSS/stylesheet.css
Hey there, wishing you a speedy development! Good luck with the overhauling.
Closes #332 
#Hacktoberfest
> fix: No longer slices ".descriptive" elements.

- lib/npc-generation/_common.ts
- src/NPCGeneration/SetupNPC.js
- src/NPCGeneration/deleteNPC.d.ts
- src/NPCGeneration/deleteNPC.js
- src/Town/components/TownListThrowaway.twee
- src/setup.d.ts
- Uses UUID string keys instead of numbers.
- Refactors `TownListThrowaway` passage file.
- Improves type definitions.
> Feature/use UUID npc keys

- src/Town/TownEdit.twee
- src/Town/js/createTownName.js
When a town is renamed, update building names as well if valid
> Building rename

- src/Settings/Breadcrumb.twee
- src/Settings/CSS/stylesheet.css
- src/Settings/PassageHeader.twee
- src/Settings/resizeHeader.js
Updates the passage header to be less jarring when scrolling.
You'll probably want to try it out and give opinions before merging.
> Update passage header

- src/Town/js/createTownName.js
Some additional names I've used in the past
> Add additional town prefixes and suffixes

- lib/faction/createRivals.ts
- lib/faction/factionData.ts
- lib/faction/setFactionJoinStats.ts
- lib/faction/setFactionName.ts
- lib/faction/setFactionResources.ts
- lib/src/utils.ts
- lib/src/weightRandom.ts
- lib/types.ts
- src/Factions/CreateFaction.js
- src/Factions/leader.js
- src/Misc/createMercenaries.js
Fixes #311 (hopefully :upside_down_face:).
> Chore - Refactor Faction data

- src/Buildings/goodsAndServices.js
I have completed the Jeweler addition. This is for the issue number 314. Please let me know if I need to redo anything. Thank you my friends :)
> Created the Jewelers

- src/NPCGeneration/npcData.js
Refactor setup.npcData.lifeEvents into an array
https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/issues/360
> Refactor setup.npcData.lifeEvents into an array

- lib/src/contentsFetcher.ts
- src/World/encounters.d.ts
- src/World/encounters.js
- src/World/events.d.ts
- src/World/events.js
- src/World/locations.d.ts
- src/World/locations.js
- src/World/miscData.js
It converts the encounters object into an array of objects.
With great effort, and a lot of swearing.
I don't think so?
Indeed.
> Convert encounters to array

- src/NPCGeneration/npcData.js
Reverts ryceg/Eigengrau-s-Essential-Establishment-Generator#363
Was a bad idea. My bad.
> Revert "Refactor setup.npcData.lifeEvents into an array"

- src/Start/BiomeGeneration.twee
- src/Town/components-edit/EditRaces.twee
- src/Town/components-edit/EditSociopolitics.twee
- src/Town/components-edit/EditTownName.twee
- src/Town/components-edit/TownEdit.twee
- src/Town/components/TownListRaces.twee
- src/Town/js/createTown.js
> closes #364

- src/Buildings/goodsAndServices.d.ts
- src/Buildings/goodsAndServices.js
- src/Tools/Widgets.twee
Refactor goods objects into arrays.
`goodsAndServices` has static type checking, but I didn't manage to test `Widgets` :frowning_face: 
#358.
Yes.
> Refactor goods objects into arrays

- .github/workflows/continous_integration.yml
- .github/workflows/release.yml
- .github/workflows/sentryRelease.yml
Adds sentry releases to the build process (I think)
No.
Duh-doi
> sentryRelease

- lib/src/defineRollDataGetter.test.ts
Add unit tests for defineRollDataGetter
Wrote unti tests
Fixes #245 
Yes
> Add tests for defineRollDataGetter

- lib/buildings/createStructure.ts
- lib/npc-generation/raceTraits.ts
- lib/town/townData.ts
- src/Tools/OutputEverything.twee
- src/Tools/outputEverything.js
Further improves outputEverything functionality for Foundry integration.
.html.
> temporary fix

- src/Buildings/goodsAndServices.js
- src/Settings/CSS/stylesheet.css
- src/Start/Start.twee
- src/Tavern/TavernOutput.twee
> Add-tavern-illustration

- lib/buildings/getSellingTalk.ts
- lib/index.ts
- src/Blacksmith/SmithySell.twee
- src/Buildings/goodsAndServices.js
Rewrites and genericizes the selling talk.
`.html`
> Rewrite selling talk

- lib/src/terrain.ts
- lib/src/weather.ts
- lib/town/_common.ts
- src/Town/Weather/js/createWeather.js
- src/Town/Weather/js/renderWeather.js
- src/setup.d.ts
Adds interfaces for Weather (and also fixes a bug when there was no weather precipitation at line 84 of `renderWeather.js`.)
Tested in `.html`.
Closes #272.
> Fix Weather Bug

- src/MiniEstablishments/Brothel/brothelData.d.ts
- src/MiniEstablishments/Brothel/brothelData.js
> Add examples

- lib/npc-generation/createReligiosity.ts
> fix random import

- CHANGELOG.md
- lib/general-store/generalStoreData.ts
- src/GeneralStore/GeneralStoreOutput.twee
> Add general store image

- CHANGELOG.md
- lib/guardhouse/_common.ts
- lib/guardhouse/guardhouseData.ts
- lib/index.ts
- lib/town/roads.ts
- src/Blacksmith/js/createSmithy.d.ts
- src/Buildings/Components/CreateNewNPC.twee
- src/Buildings/goodsAndServices.js
- src/Docks/createDocks.d.ts
- src/Factions/FactionProfile.twee
- src/Factions/components/FactionGovernance.twee
- src/Factions/components/FactionPolitics.twee
- src/Factions/components/FactionResources.twee
- src/Factions/components/PolicingFaction.twee
- src/GeneralStore/GeneralStoreOutput.twee
- src/GeneralStore/JS/createGeneralStore.d.ts
- src/GeneralStore/JS/createGeneralStore.js
- src/MiniEstablishments/Brothel/createBrothel.d.ts
- src/MiniEstablishments/Graveyard/GraveyardOutput.twee
- src/MiniEstablishments/Guardhouse/GuardhouseOutput.twee
- src/MiniEstablishments/Guardhouse/createGuardhouse.d.ts
- src/MiniEstablishments/Guardhouse/createGuardhouse.js
- src/Settings/Setting.js
- src/Start/StoryInit.twee
- src/Town/js/createNewBuilding.js
- src/Town/js/createStartBuildings.js
- src/Town/js/findPoliceSource.js
- src/setup.d.ts
Adds the guardhouse, prepared for release.
`.html`
> Add-guardhouse

- lib/npc-generation/_common.ts
- lib/town/roads.ts
Adds the Namesake interface
`.html`
> Add-Namesake-interface

- .github/pull_request_template.md
> Remove-GPL-talk

- lib/npc-generation/_common.ts
- lib/npc-generation/createReligiosity.ts
- lib/src/closestMatch.ts
- lib/town/_common.ts
- src/NPCGeneration/NPCProfile/NPCProfile.twee
- src/Town/js/createTown.js
Thanks for your patience as I try to figure this out :)
> Add two dimensional religion array.

- lib/npc-generation/createReligiosity.ts
> add remainders

- src/NPCGeneration/checkRaces.ts
- src/main.ts
- src/setup.d.ts
This converts the `checkRaces ` module to TypeScript.
> Convert checkRaces to ts

- lib/src/utils.ts
- src/NPCGeneration/deleteNPC.d.ts
- src/NPCGeneration/deleteNPC.ts
- src/main.ts
Converts the `deleteNPC` module to TypeScript.
> Convert delete npc to ts

- src/NPCGeneration/NPCProfile/Components/NPCLifeEvents.twee
- src/NPCGeneration/NPCProfile/NPCProfileLKMarkdown.twee
- src/NPCGeneration/NPCProfile/components-edit/NPCProfileEdit.twee
- src/NPCGeneration/getLifeEvents.ts
- src/main.ts
This extracts the life events string generation from various twine files into a single typescript function.
> Move life events printing to js function

- lib/inactive/plothookData.ts
- src/NPCGeneration/createHistory.ts
- src/NPCGeneration/profile.ts
- src/PlotHook/plothooks.ts
- src/Tavern/js/getWakeUpByWealth.ts
- src/Tools/findViaKey.ts
- src/main.ts
Adds profile to TypeScript
Not tested, but should work just fine.
Nah.
> Convert-profile-to-TypeScript

- src/Buildings/deleteBuilding.d.ts
- src/Buildings/deleteBuilding.js
- src/Buildings/deleteBuilding.ts
- src/main.ts
Converts `deleteBuilding` to TypeScript.
> Convert deleteBuilding to TS

- src/World/urlSeed.d.ts
- src/World/urlSeed.ts
- src/main.ts
Converts `urlSeed` to typescript.
> Convert module urlSeed

- src/Settings/getPriceMod.ts
- src/main.ts
Converts `getPriceModifier` to typescript.
Also generalizes the input interface.
> Convert get price mod

- src/Factions/deleteFaction.d.ts
- src/Factions/deleteFaction.ts
- src/Factions/leader.d.ts
- src/Factions/leader.ts
- src/main.ts
> Convert-faction-stuff

- src/NPCGeneration/Relationships/createFamilyMembers.ts
- src/NPCGeneration/socialClass.ts
Converts the `SetupSocialClass` into Typescript `socialClass` module.
> Ts convert/social class

- src/NPCGeneration/profile.ts
- src/World/encounters.ts
- src/World/graveStone.ts
Imports `profile` instead of using it via `setup.profile` where applicable.
Verified that no errors was thrown.
> ts-convert/import profile module

- lib/src/terrain.ts
- lib/src/weather.ts
- src/World/createWeather.ts
- src/World/renderWeather.ts
- src/World/toCelsius.ts
- src/main.ts
Converts the weather to typescript.
Tested, seems to have an issue with some untouched files for some reason- 
```
No name was provided for external module 'src/NPCGeneration/profile' in output.globals – guessing 'profile$1'
No name was provided for external module 'src/Tools/findViaKey' in output.globals – guessing 'findViaKey$1'
No name was provided for external module 'src/Tools/getPriceMod' in output.globals – guessing 'getPriceMod$1'
```
No
> Convert-weather

- lib/src/terrain.ts
- lib/src/weather.ts
- src/Town/Weather/js/createWeather.js
- src/Town/Weather/js/renderWeather.js
- src/Town/Weather/js/toCelsius.js
- src/main.ts
Reverts ryceg/Eigengrau-s-Essential-Establishment-Generator#490
> Revert "Convert-weather"

- src/Factions/components/PolicingFaction.twee
- src/Start/RoadsList.twee
- src/Town/TownOutput.twee
> Fix-roads-list

- lib/religion/religion.ts
Added Poseidon, Hades, Hera, Hermes, Dionysus, Artemis, Apollo, Aphrodite, Demeter and Athena
Added Blessing/Curses options
> Added Many Gods

- lib/religion/religion.ts
Finished the Basic Draft for the Greek Gods. 
All portfolios, titles and domains have been added
Still need to add the possessions, avatars, symbols and appearances for many gods
> Added more data for deities

- src/Settings/CSS/stylesheet.css
- src/Tools/Exports/exportAsHtml.js
- src/Town/TownOutput.twee
- src/Town/js/createStartBuildings.js
> Change style of details to be h3

- lib/religion/religion.ts
Had to add in the option of whether gods were alive or dead, added another option for gender that was 'shape-shifter' and what faction a god was in. Thanks Loki
Added the option to have a 'Realm'
Added Odin, Thor, Loki, Frigga, Freyr, Freyja
> Started on the Norse Gods

- lib/religion/religion.ts
Added Some Norse Gods and some deatils for Greek Gods
> Details and Norse

- src/Settings/StoryStuff/StoryShare.twee
> Edit-Tweet

- lib/religion/religion.ts
Added descriptions for some of the gods, added details. Added details to some of the god's Followers. Added some of the Tactics.
> Added more Details to Greek Gods

- CHANGELOG.md
- README.md
- src/Meta/Contributors.twee
- src/Meta/Credits.twee
- src/Meta/FunStats.twee
- src/Meta/Legal.twee
- src/Meta/PatreonSupporters.twee
- src/Settings/StoryStuff/StoryAuthor.twee
> Add live badges

- src/Castle/CastleOutput.twee
- src/Castle/Components/CastleDungeon.twee
- src/Castle/Components/StandaloneDungeon.twee
- src/Castle/Dungeon.twee
- src/MiniEstablishments/TownSquare/TownSquareOutput.twee
- src/Settings/Setting.js
- src/Start/BuildingLink.twee
- src/Start/BuildingsList.twee
- src/Start/CreateBuilding.twee
- src/Start/RoadsList.twee
- src/Tools/profile.js
Adds cleanupWikifierOutput and fixes an issue with castle output
Tested in html
Closes #542
> Fix-Castle-output

- CHANGELOG.md
- lib/buildings/findBuildingRelationship.ts
- src/Blacksmith/js/blacksmithProject.js
- src/Blacksmith/js/createSmithyName.js
- src/Buildings/Components/BuildingRelationshipsTable.twee
- src/Buildings/Components/buildingRelationshipNpc.js
- src/Castle/castleData.js
- src/Castle/createCastlePopulation.js
- src/GeneralStore/JS/createGeneralStoreName.js
- src/MiniEstablishments/Brothel/brothelData.ts
- src/NPCGeneration/NPCProfile/Components/NPCRelationshipsTable.twee
- src/NPCGeneration/NPCProfile/components-edit/NPCAddRelationship.twee
- src/NPCGeneration/NPCProfile/components-edit/NPCProfileEdit.twee
- src/NPCGeneration/NPCProfile/components-edit/NPCRelationshipsTableEdit.twee
- src/NPCGeneration/Relationships/createFriends.ts
- src/NPCGeneration/Relationships/createRelationship.ts
- src/NPCGeneration/SetupDeath.js
- src/NPCGeneration/createDebt.ts
- src/NPCGeneration/createHistory.ts
- src/NPCGeneration/expandNPC.ts
- src/NPCGeneration/npcData.js
- src/PlotHook/plothooks.ts
- src/Tavern/js/createTavern.ts
Adds the ability to edit a relationship between two NPCs, and even create new relationships.
Tested in html.
Closes #546
> Create new relationships

- CHANGELOG.md
- src/Buildings/Components/NPCListboxes.twee
- src/Factions/components/CreateFactionNpc.twee
- src/Meta/Popup.twee
- src/Misc/CreateRandomNPC.twee
- src/NPCGeneration/NPCProfile/Components/NPCHeader.twee
- src/Settings/CSS/print.css
- src/Start/CreateBuilding.twee
- src/Start/Start.twee
- src/Tavern/TavernOutput.twee
- src/Town/TownOutput.twee
- src/Town/components-edit/EditTownName.twee
- src/Town/components/CreateFaction.twee
- src/Town/components/TownListProfessions.twee
- src/World/CreateScenario.twee
Adds the css media query for print requests.
Lots of testing in html
Improves #539.
> Initial commit

- CHANGELOG.md
- lib/buildings/_common.ts
- lib/buildings/createBuilding.ts
- lib/buildings/homeData.ts
- lib/npc-generation/_common.ts
- lib/npc-generation/familyRelationships.ts
- lib/npc-generation/lifestyleStandards.ts
- lib/town/roads.ts
- src/GeneralStore/GeneralStoreOutput.twee
- src/NPCGeneration/NPCProfile/NPCProfile.twee
- src/NPCGeneration/Relationships/createFamilyMembers.ts
- src/Roads/RoadTables.twee
- src/Tavern/js/createTavern.ts
Adds NPCs to roads.
Tested in html
No.
> Add NPC to roads

- src/Start/StoryInit.twee
> testing release 

- .github/workflows/release.yml
> Try and fix the release bug

- lib/religion/testCustom.json
- src/Settings/CSS/viewport.css
Reverts viewport stuff, updates testCustom.json
> Revert viewport

- CHANGELOG.md
- lib/religion/getPantheon.ts
- src/Religion/Components/DeityRelationships.twee
- src/Religion/DeityProfile.twee
- src/Settings/CustomImages.twee
- src/Tools/Exports/OutputEverything.twee
- src/Tools/Exports/outputEverything.ts
- src/Tools/findViaKey.ts
- src/Town/components-edit/EditReligion.twee
Adds the getPantheonDeity function, fixes an issue where deities that were at 0% weren't working in the editor.
Tested in html
> Add-getPantheonDeities

- lib/npc-generation/bmiDescriptions.data.json
- lib/npc-generation/raceTraits.ts
- yarn.lock
Closes two minor bugs and upgrades dependencies.
> Close bugs

- src/main.ts
Corrects syntax
yarn build, now I "only" get errors about circular dependencies, but it continues until running tweego:
```
Compiling scripts...
@rollup/plugin-replace: 'preventAssignment' currently defaults to false. It is recommended to set this option to `true`, as the next major version will default this option to `true`.
(node:29059) UnhandledPromiseRejectionWarning: Error: Could not resolve './NPCGeneration/SetupDeath' from src/main.ts
at error (/media/pm/Data/Documents/github/Eigengrau-s-Essential-Establishment-Generator-master/node_modules/rollup/dist/shared/rollup.js:5309:30)
at ModuleLoader.handleResolveId (/media/pm/Data/Documents/github/Eigengrau-s-Essential-Establishment-Generator-master/node_modules/rollup/dist/shared/rollup.js:18579:24)
at …
```
> Changed SetupDeath to setupDeath to prevent breakin yarn build

- src/Town/components/TownListNpcs.twee
This provides a crude means to sort the NPC values
Ran using a built veryion
Yes, #290 
This is improper, but i'm not entirely sure how to move the JS into a separate file... Are you able to show me?
> Sorting NPC values

- .gitignore
- lib/npc-generation/fetchProfessionChance.test.ts
- lib/npc-generation/fetchProfessionChance.ts
- lib/src/findInContainer.ts
- lib/src/math.test.ts
- lib/src/math.ts
Refactor fetchProfessionChance and adding unit tests
- Extracting filtering work into separate methods
- Moving some math-y stuff to separate file and adding unit tests
Unit tests + poking around the NPC list in the compiled file
As I mentioned in Discord, I'm working my way to fixing https://github.com/ryceg/Eigengrau-s-Essential-Establishment-Generator/issues/263 - but I'm finding lots of places to clean up along the way. This is one of them.
> Refactor fetch profession chance

- lib/buildings/BuildingToCreate.ts
- lib/buildings/_common.ts
- lib/buildings/assertBuildingHasNPC.ts
- lib/buildings/createBuilding.ts
- lib/buildings/createStructure.ts
- lib/buildings/cullBuildings.ts
- src/Buildings/assertBuildingExists.ts
- src/Buildings/goodsAndServices.ts
- src/Buildings/goodsAndServices/bakery.ts
- src/Buildings/goodsAndServices/barber.ts
- src/Buildings/goodsAndServices/butcher.ts
- src/Buildings/goodsAndServices/cobbler.ts
- src/Buildings/goodsAndServices/confectionery.ts
- src/Buildings/goodsAndServices/fletcher.ts
- src/Buildings/goodsAndServices/florist.ts
- src/Buildings/goodsAndServices/jeweller.ts
- src/Buildings/goodsAndServices/tailor.ts
- src/Buildings/initGoodsAndServices.js
- src/Buildings/populateGoodsAndServices.ts
- src/Castle/castleData.js
- src/Settings/CSS/stylesheet.css
- src/Start/StoryInit.twee
- src/World/urlSeed.ts
- src/main.ts
Fixes the mess I made with converting the goods and services to typescript.
Tested in html. Compiles like a charm.
No
> Fix-Goods-and-Services

- lib/buildings/getSellingTalk.ts
- lib/faction/setFactionAge.ts
- lib/faction/setFactionReputation.ts
- lib/faction/setFactionResources.ts
- lib/general-store/generalStoreRenders.test.ts
- lib/general-store/generalStoreRenders.ts
- lib/npc-generation/religiosity/createReligiosity.ts
- lib/npc-generation/setAge.ts
- lib/npc-generation/setRace.ts
- lib/npc-generation/traits/getTraitDescriptors.ts
- lib/src/rollFromTable.test.ts
- lib/src/rollFromTable.ts
Adds and applies a new `getRolledFromTable` utility function.
> add getRolledFromTable function

- lib/alchemist/alchemistData.ts
- lib/buildings/_common.ts
- lib/general-store/generalStoreData.ts
- lib/smithy/smithyData.ts
- lib/src/rollFromTable.ts
- lib/tavern/_common.ts
- lib/town/townData.ts
- Starts unifying `rollData`.
- Removes unused `hasRolls` & some other rolls-related code.
> Clean up roll data

- lib/buildings/createReciprocalRelationship.ts
- lib/npc-generation/_common.ts
- src/Castle/createCastle.d.ts
- src/Castle/createDungeon.d.ts
- src/NPCGeneration/setupDeath.ts
Fixes `src/*`-import in `lib` by migrating the `DeadNPC` type.
> Move DeadNPC interface to lib

- src/Tavern/js/createTavern.ts
Fixes a bug with trying to access the old tavern roll data
> fix tavern roll data access

- lib/alchemist/alchemistRollData.ts
- lib/brothel/brothelRollData.ts
- lib/buildings/BuildingToCreate.ts
- lib/buildings/findReciprocalRelationships.ts
- lib/npc-generation/createNamesake.ts
- lib/npc-generation/swapNPCs.ts
- lib/religion/getPantheon.ts
- lib/religion/getPredominantReligion.ts
- lib/src/terrain.ts
- lib/town/_common.ts
Fixes imports from `lib` in `lib`.
> fix imports of lib in lib

- src/Docks/createDocks.js
- src/MiniEstablishments/Guardhouse/createGuardhouse.ts
Fixes a couple of issues from the recent roll data refactoring
> fix incorrect roll data accessing

- lib/index.ts
- lib/temple/templeData.ts
- src/MiniEstablishments/Temple/CreateTemple.js
Moves the temple data object to `lib`.
> Move temple data to lib

- lib/src/weather.ts
- src/Town/Weather/js/createWeather.js
- src/Town/Weather/js/renderWeather.js
- src/World/CreateScenario.twee
This computes the weather readouts when needed, instead of storing them on the weather object itself.
> Calculate weather readout instead of storing it

- lib/src/dice.ts
Replaces leftover legacy logging.
> Replace old console.log in dice.ts

- lib/general-store/generalStoreData.ts
> Clean up generalStoredata impors

- lib/src/shareMenu.ts
Minor cleanup of the `shareMenu` fuction.
> Refactor shareMenu function

- lib/docks/shipRollData.ts
- lib/index.ts
- src/Docks/docks.js
> Extract ship roll data to lib

- CHANGELOG.md
- package.json
- src/Start/StoryInit.twee
> Update to 2.9
